import { Inter } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import RootComponent from "@/components/RootComponent";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="p-[1.6rem]">
            <Sidebar />
            <main className="lg:ml-[7.7rem]">
                <Header />  
                <div className="">
                  <RootComponent>
                    {children}
                  </RootComponent>
                </div>
            </main>     
        </div> 
      </body>
    </html>
  );
}
